title: "Matthew Poole Chicano"
description: "Indie Game Developer | Aspiring Junior Developer | IT Support Enthusiast"
logo: "/images/pfp.png"
theme: jekyll-theme-minimal
favicon: "/favicon.ico"
markdown: kramdown
