title: "Matthew Poole Chicano"
description: "IT Enthusiast | Indie Game Dev | Linux Nerd"
avatar: "/images/pfp.png"
menu: [ "Home", "Projects", "About" ]
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme
